### ISSUE TITLE
"Request is empty" Error When running the Java TDLib Application

### ISSUE THREAD

**Issue by patzu** [tdlib/td#2913]
I have updated the TDLib to its latest version and I am trying to run the default java example for TDLib, but getting bellow message:

```
Receive an error:
Error {
  code = 400
  message = "Request is empty"
}
```

**Comment by levlam** [comment]
I've pushed a likely fix to master.

**Comment by patzu** [comment]
I've updated and rebuilt with the latest changes from master, but I'm still encountering the same error: Error 
```
{
 code = 400, 
 message = "Request is empty" 
}
``` 
The build process takes a significant amount of time, and seeing the error persist after all that effort is quite frustrating. Could you please verify if the changes were intended to address this issue? It would be helpful to confirm that the fix works before I attempt another lengthy build, as I have been trying to resolve this error for several days.

**Comment by levlam** [comment]
Could you set log verbosity level to 10 in the line
`Client.execute(new TdApi.SetLogVerbosityLevel(0));`
and send the log to https://t.me/tdlib_bot?

**Comment by patzu** [comment]
I've set the log verbosity level to 10 as suggested and have run the example. The tdlib.log file has been created and sent to the specified Telegram bot at https://t.me/tdlib_bot. Please let me know if there's anything else I can do to help resolve this issue.

**Comment by levlam** [comment]
You use a year old TDLib version, not the latest one. You can see the exact version and commit number in the TDLib log.
